// =============================================================================
// processLinkedListCollision @ 0x006abc40
// Function range: 0x006abc40 -- 0x006abd88 (329 bytes)
// Generated by Ghidra headless analysis
// =============================================================================

// =============================================================================
// SECTION 1: DECOMPILATION
// =============================================================================


undefined * __fastcall
processLinkedListCollision(int *param_1,float *param_2,uint *param_3,uint param_4)

{
  int iVar1;
  uint uVar2;
  int iVar3;
  undefined *puVar4;
  undefined4 *puVar5;
  undefined **ppuVar6;
  undefined *local_28;
  undefined *local_24;
  undefined *local_20;
  undefined *local_1c;
  undefined *local_18;
  undefined *local_14;
  undefined *local_10;
  undefined *local_c;
  undefined *local_8;
  
  if ((param_4 & 0xf0000f) != 0) {
    local_8 = (undefined *)param_1[2];
    local_10 = (undefined *)param_1;
    local_c = (undefined *)param_2;
    if ((((uint)local_8 & 1) != 0) || (local_8 == (undefined *)0x0)) {
      local_8 = (undefined *)0x0;
    }
    while ((puVar4 = local_8, ((uint)local_8 & 1) == 0 && (local_8 != (undefined *)0x0))) {
      iVar1 = *(int *)(local_8 + 4);
      if (((*(ushort *)(iVar1 + 0xc) & 0x100) == 0) &&
         ((*(undefined **)(iVar1 + 0x8c) != PTR_00c89f20 && (*(int *)(iVar1 + 0x88) != 0)))) {
        if (*(int *)(iVar1 + 0x180) == 0 && *(int *)(iVar1 + 0x184) == 0) {
          uVar2 = param_4 & 0xf;
        }
        else {
          uVar2 = param_4 & 0xf00000;
        }
        if (uVar2 != 0) {
          if (-1 < (char)*(ushort *)(iVar1 + 0xc)) {
            return (undefined *)0x0;
          }
          puVar5 = (undefined4 *)(iVar1 + 0x14c);
          ppuVar6 = &local_28;
          for (iVar3 = 6; iVar3 != 0; iVar3 = iVar3 + -1) {
            *ppuVar6 = (undefined *)*puVar5;
            puVar5 = puVar5 + 1;
            ppuVar6 = ppuVar6 + 1;
          }
          if (((((float)local_28 < *(float *)(local_c + 0xc) !=
                 ((float)local_28 == *(float *)(local_c + 0xc))) &&
               ((float)local_24 < *(float *)(local_c + 0x10) !=
                ((float)local_24 == *(float *)(local_c + 0x10)))) &&
              ((float)local_20 < *(float *)(local_c + 0x14) !=
               ((float)local_20 == *(float *)(local_c + 0x14)))) &&
             (((*(float *)local_c <= (float)local_1c && (*(float *)(local_c + 4) <= (float)local_18)
               ) && (*(float *)(local_c + 8) <= (float)local_14)))) {
            addGeometryToBuffer((float *)local_c,iVar1,param_3);
            puVar4 = local_8;
          }
          *(undefined **)(iVar1 + 0x8c) = PTR_00c89f20;
        }
      }
      local_8 = *(undefined **)(puVar4 + *(int *)local_10 + 4);
    }
  }
  return (undefined *)0x1;
}



// =============================================================================
// SECTION 2: FULL DISASSEMBLY
// =============================================================================
//
// 0x006abc40  55                        PUSH EBP
// 0x006abc41  8b ec                     MOV EBP,ESP
// 0x006abc43  83 ec 24                  SUB ESP,0x24
// 0x006abc46  53                        PUSH EBX
// 0x006abc47  8b c1                     MOV EAX,ECX
// 0x006abc49  8b 4d 0c                  MOV ECX,dword ptr [EBP + 0xc]
// 0x006abc4c  f7 c1 0f 00 f0 00         TEST ECX,0xf0000f
// 0x006abc52  56                        PUSH ESI
// 0x006abc53  57                        PUSH EDI
// 0x006abc54  89 55 f8                  MOV dword ptr [EBP + -0x8],EDX
// 0x006abc57  89 45 f4                  MOV dword ptr [EBP + -0xc],EAX
// 0x006abc5a  0f 84 1b 01 00 00         JZ 0x006abd7b
// 0x006abc60  8b 40 08                  MOV EAX,dword ptr [EAX + 0x8]
// 0x006abc63  a8 01                     TEST AL,0x1
// 0x006abc65  75 04                     JNZ 0x006abc6b
// 0x006abc67  85 c0                     TEST EAX,EAX
// 0x006abc69  75 07                     JNZ 0x006abc72
// 0x006abc6b  33 d2                     XOR EDX,EDX
// 0x006abc6d  89 55 fc                  MOV dword ptr [EBP + -0x4],EDX
// 0x006abc70  eb 06                     JMP 0x006abc78
// 0x006abc72  89 45 fc                  MOV dword ptr [EBP + -0x4],EAX
// 0x006abc75  8b 55 fc                  MOV EDX,dword ptr [EBP + -0x4]
// 0x006abc78  f6 c2 01                  TEST DL,0x1
// 0x006abc7b  0f 85 fa 00 00 00         JNZ 0x006abd7b
// 0x006abc81  85 d2                     TEST EDX,EDX
// 0x006abc83  0f 84 f2 00 00 00         JZ 0x006abd7b
// 0x006abc89  8b 5a 04                  MOV EBX,dword ptr [EDX + 0x4]
// 0x006abc8c  66 8b 43 0c               MOV AX,word ptr [EBX + 0xc]
// 0x006abc90  f6 c4 01                  TEST AH,0x1
// 0x006abc93  0f 85 c1 00 00 00         JNZ 0x006abd5a
// 0x006abc99  8b 35 20 9f c8 00         MOV ESI,dword ptr [0x00c89f20]
// 0x006abc9f  39 b3 8c 00 00 00         CMP dword ptr [EBX + 0x8c],ESI
// 0x006abca5  0f 84 af 00 00 00         JZ 0x006abd5a
// 0x006abcab  8b b3 88 00 00 00         MOV ESI,dword ptr [EBX + 0x88]
// 0x006abcb1  85 f6                     TEST ESI,ESI
// 0x006abcb3  0f 84 a1 00 00 00         JZ 0x006abd5a
// 0x006abcb9  8b b3 80 01 00 00         MOV ESI,dword ptr [EBX + 0x180]
// 0x006abcbf  0b b3 84 01 00 00         OR ESI,dword ptr [EBX + 0x184]
// 0x006abcc5  74 08                     JZ 0x006abccf
// 0x006abcc7  f7 c1 00 00 f0 00         TEST ECX,0xf00000
// 0x006abccd  eb 03                     JMP 0x006abcd2
// 0x006abccf  f6 c1 0f                  TEST CL,0xf
// 0x006abcd2  0f 84 82 00 00 00         JZ 0x006abd5a
// 0x006abcd8  84 c0                     TEST AL,AL
// 0x006abcda  0f 89 90 00 00 00         JNS 0x006abd70
// 0x006abce0  8d b3 4c 01 00 00         LEA ESI,[EBX + 0x14c]
// 0x006abce6  b9 06 00 00 00            MOV ECX,0x6
// 0x006abceb  8d 7d dc                  LEA EDI,[EBP + -0x24]
// 0x006abcee  f3 a5                     MOVSD.REP ES:EDI,ESI
// 0x006abcf0  d9 45 dc                  FLD float ptr [EBP + -0x24]
// 0x006abcf3  8b 4d f8                  MOV ECX,dword ptr [EBP + -0x8]
// 0x006abcf6  d8 59 0c                  FCOMP float ptr [ECX + 0xc]
// 0x006abcf9  df e0                     FNSTSW AX
// 0x006abcfb  f6 c4 41                  TEST AH,0x41
// 0x006abcfe  7a 4e                     JP 0x006abd4e
// 0x006abd00  d9 45 e0                  FLD float ptr [EBP + -0x20]
// 0x006abd03  d8 59 10                  FCOMP float ptr [ECX + 0x10]
// 0x006abd06  df e0                     FNSTSW AX
// 0x006abd08  f6 c4 41                  TEST AH,0x41
// 0x006abd0b  7a 41                     JP 0x006abd4e
// 0x006abd0d  d9 45 e4                  FLD float ptr [EBP + -0x1c]
// 0x006abd10  d8 59 14                  FCOMP float ptr [ECX + 0x14]
// 0x006abd13  df e0                     FNSTSW AX
// 0x006abd15  f6 c4 41                  TEST AH,0x41
// 0x006abd18  7a 34                     JP 0x006abd4e
// 0x006abd1a  d9 45 e8                  FLD float ptr [EBP + -0x18]
// 0x006abd1d  d8 19                     FCOMP float ptr [ECX]
// 0x006abd1f  df e0                     FNSTSW AX
// 0x006abd21  f6 c4 01                  TEST AH,0x1
// 0x006abd24  75 28                     JNZ 0x006abd4e
// 0x006abd26  d9 45 ec                  FLD float ptr [EBP + -0x14]
// 0x006abd29  d8 59 04                  FCOMP float ptr [ECX + 0x4]
// 0x006abd2c  df e0                     FNSTSW AX
// 0x006abd2e  f6 c4 01                  TEST AH,0x1
// 0x006abd31  75 1b                     JNZ 0x006abd4e
// 0x006abd33  d9 45 f0                  FLD float ptr [EBP + -0x10]
// 0x006abd36  d8 59 08                  FCOMP float ptr [ECX + 0x8]
// 0x006abd39  df e0                     FNSTSW AX
// 0x006abd3b  f6 c4 01                  TEST AH,0x1
// 0x006abd3e  75 0e                     JNZ 0x006abd4e
// 0x006abd40  8b 45 08                  MOV EAX,dword ptr [EBP + 0x8]
// 0x006abd43  50                        PUSH EAX
// 0x006abd44  8b d3                     MOV EDX,EBX
// 0x006abd46  e8 45 00 00 00            CALL 0x006abd90
// 0x006abd4b  8b 55 fc                  MOV EDX,dword ptr [EBP + -0x4]
// 0x006abd4e  8b 0d 20 9f c8 00         MOV ECX,dword ptr [0x00c89f20]
// 0x006abd54  89 8b 8c 00 00 00         MOV dword ptr [EBX + 0x8c],ECX
// 0x006abd5a  8b 45 f4                  MOV EAX,dword ptr [EBP + -0xc]
// 0x006abd5d  8b 00                     MOV EAX,dword ptr [EAX]
// 0x006abd5f  8b 4c 10 04               MOV ECX,dword ptr [EAX + EDX*0x1 + 0x4]
// 0x006abd63  03 c2                     ADD EAX,EDX
// 0x006abd65  89 4d fc                  MOV dword ptr [EBP + -0x4],ECX
// 0x006abd68  8b 4d 0c                  MOV ECX,dword ptr [EBP + 0xc]
// 0x006abd6b  e9 05 ff ff ff            JMP 0x006abc75
// 0x006abd70  5f                        POP EDI
// 0x006abd71  5e                        POP ESI
// 0x006abd72  33 c0                     XOR EAX,EAX
// 0x006abd74  5b                        POP EBX
// 0x006abd75  8b e5                     MOV ESP,EBP
// 0x006abd77  5d                        POP EBP
// 0x006abd78  c2 08 00                  RET 0x8
// 0x006abd7b  5f                        POP EDI
// 0x006abd7c  5e                        POP ESI
// 0x006abd7d  b8 01 00 00 00            MOV EAX,0x1
// 0x006abd82  5b                        POP EBX
// 0x006abd83  8b e5                     MOV ESP,EBP
// 0x006abd85  5d                        POP EBP
// 0x006abd86  c2 08 00                  RET 0x8
//
// Total instructions: 108

// =============================================================================
// SECTION 3: PROLOGUE (first 30 instructions)
// =============================================================================
//
// 0x006abc40  55                        PUSH EBP
// 0x006abc41  8b ec                     MOV EBP,ESP
// 0x006abc43  83 ec 24                  SUB ESP,0x24
// 0x006abc46  53                        PUSH EBX
// 0x006abc47  8b c1                     MOV EAX,ECX
// 0x006abc49  8b 4d 0c                  MOV ECX,dword ptr [EBP + 0xc]
// 0x006abc4c  f7 c1 0f 00 f0 00         TEST ECX,0xf0000f
// 0x006abc52  56                        PUSH ESI
// 0x006abc53  57                        PUSH EDI
// 0x006abc54  89 55 f8                  MOV dword ptr [EBP + -0x8],EDX
// 0x006abc57  89 45 f4                  MOV dword ptr [EBP + -0xc],EAX
// 0x006abc5a  0f 84 1b 01 00 00         JZ 0x006abd7b
// 0x006abc60  8b 40 08                  MOV EAX,dword ptr [EAX + 0x8]
// 0x006abc63  a8 01                     TEST AL,0x1
// 0x006abc65  75 04                     JNZ 0x006abc6b
// 0x006abc67  85 c0                     TEST EAX,EAX
// 0x006abc69  75 07                     JNZ 0x006abc72
// 0x006abc6b  33 d2                     XOR EDX,EDX
// 0x006abc6d  89 55 fc                  MOV dword ptr [EBP + -0x4],EDX
// 0x006abc70  eb 06                     JMP 0x006abc78
// 0x006abc72  89 45 fc                  MOV dword ptr [EBP + -0x4],EAX
// 0x006abc75  8b 55 fc                  MOV EDX,dword ptr [EBP + -0x4]
// 0x006abc78  f6 c2 01                  TEST DL,0x1
// 0x006abc7b  0f 85 fa 00 00 00         JNZ 0x006abd7b
// 0x006abc81  85 d2                     TEST EDX,EDX
// 0x006abc83  0f 84 f2 00 00 00         JZ 0x006abd7b
// 0x006abc89  8b 5a 04                  MOV EBX,dword ptr [EDX + 0x4]
// 0x006abc8c  66 8b 43 0c               MOV AX,word ptr [EBX + 0xc]
// 0x006abc90  f6 c4 01                  TEST AH,0x1
// 0x006abc93  0f 85 c1 00 00 00         JNZ 0x006abd5a

// =============================================================================
// SECTION 4: ALL RET INSTRUCTIONS (stack cleanup indicator)
// =============================================================================
//
// 0x006abd78  c2 08 00                  RET 0x8
// 0x006abd86  c2 08 00                  RET 0x8

// =============================================================================
// SECTION 5: XREFS TO 0x006abc40 (callers)
// =============================================================================
//
//   0x006aad4c  [UNCONDITIONAL_CALL]  in processGeometryBoundsCheck (0x006aaab0)
//   0x006ab4a1  [UNCONDITIONAL_CALL]  in processTerrainChunkMeshGeneration (0x006aadc0)
//
//   Total callers: 2

// =============================================================================
// SECTION 6: XREFS FROM 0x006abc40 (callees)
// =============================================================================
//
//   0x006abd90  addGeometryToBuffer
//
//   Total callees: 1

